# Uncomment the next line to define a global platform for your project
platform :ios, '14.3'

target 'iOSPokedex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSPokedex
  pod 'SwiftLint'
  pod 'lottie-ios'
  pod 'Alamofire', '~> 5.2'
  pod 'SDWebImage', '~> 5.0'
  pod "PromiseKit", "~> 6.8"

end
